### ISSUE TITLE
Job stuck on Running

### ISSUE THREAD

**Issue by ldmuniz** [romanzipp/Laravel-Queue-Monitor#48] opened 2021-01-21 19:08 UTC
Sometimes, when the job hit the timeout, another attempt is created and the original Job stucks on "Running".
I suggest a little change in jobStarted function at romanzipp\QueueMonitor\Services\QueueMonitor.php

Original:
```   
protected static function jobStarted(JobContract $job): void
    {
        if ( ! self::shouldBeMonitored($job)) {
            return;
        }

        $now = Carbon::now();

        $model = self::getModel();

        $model::query()->create(['job_id' => self::getJobId($job)],[            
            'name' => $job->resolveName(),
            'queue' => $job->getQueue(),
            'started_at' => $now,
            'started_at_exact' => $now->format(self::TIMESTAMP_EXACT_FORMAT),
            'attempt' => $job->attempts(),
        ]);
    }
  ```

  Suggestion:
```   
    protected static function jobStarted(JobContract $job): void
    {
        if ( ! self::shouldBeMonitored($job)) {
            return;
        }

        $now = Carbon::now();

        $model = self::getModel();

        $model::query()->updateOrCreate(['job_id' => self::getJobId($job)],[            
            'name' => $job->resolveName(),
            'queue' => $job->getQueue(),
            'started_at' => $now,
            'started_at_exact' => $now->format(self::TIMESTAMP_EXACT_FORMAT),
            'attempt' => $job->attempts(),
        ]);
    }
  ```

**Comment by romanzipp** [comment] 2021-01-22 07:05
Sadly I can not reproduce this issue. 

When executing the following test job which takes 30 seconds to run but specifying `--timeout=5` with the `artisan queue:work` command, the Queue monitor will correctly mark the job as failed.

Maybe the job is hitting your configured [`max_execution_time`](https://www.php.net/manual/en/info.configuration.php#ini.max-execution-time) threshold? In this case it's not possible to mark the previous attempt as failed since the PHP process will be killed immediately. The following attempt will also generate a new `job_id`

```php
namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use romanzipp\QueueMonitor\Traits\IsMonitored;

class TestJob implements ShouldQueue
{
    use Dispatchable;
    use InteractsWithQueue;
    use IsMonitored;
    use Queueable;
    use SerializesModels;
    use IsMonitored;

    public function handle()
    {
        sleep(30);
    }

    public function failed()
    {
        logger('TIMEOUT OCCURED');
    }
}
```

![Screen Shot 2021-01-22 at 08 01 22](https://user-images.githubusercontent.com/11266773/105457971-07236580-5c88-11eb-9282-412ace5235cf.png)

**Comment by javis** [comment] 2021-03-02 16:45
Same happened to me, I have cases when a job would stop running (I think it is the OS killing the process, still looking into it) and the job would be stuck as running forever

**Comment by juanparati** [comment] 2021-05-20 12:41
There another possible reason that keep some jobs stuck on running and is when jobs are distributed across multiple Laravel workers on different servers (distributed system).


See https://github.com/romanzipp/Laravel-Queue-Monitor/pull/68 for more details.

**Comment by evaleries** [comment] 2021-10-17 23:53
I have the same issue with this. 
Instead of update the existing record, this package creates new row.

How to reproduce:
1. Set a new jobs (pending jobs)
2. Run the worker
3. In the middle of running, interrupt the worker and close it
4. Restart the worker

You'll see a new record in database. Take a look at my example below
<details>
<summary>screenshot of duplicate row and job stuck on running</summary>

![image](https://user-images.githubusercontent.com/48923153/137649386-734a1252-78ff-4c93-95b7-e03581bceae4.png)

As you can see, there are 2 FakeJob with number 21.
This package should've updated the FakeJob 21 instead creating a new one.
</details>

I think the given solution by @ldmuniz should work

**Closed** 2022-11-22 10:58 UTC
Labels: bug, question
